### github repo request
GET https://api.github.com/orgs/gyroflow/repos
Accept: application/vnd.github+json
Authorization: Bearer {{github_token}}
X-GitHub-Api-Version: 2022-11-28


### correct request
GET http://localhost:8080/v1/repos/AlexeyZatsepin?page=0&size=20
Accept: application/json
Authorization: Bearer {{cognito_token}}


### wrong header
GET http://localhost:8080/v1/repos/AlexeyZatsepin?page=0&size=20
Accept: application/xml
Authorization: Bearer {{cognito_token}}


### not existing repository
GET http://localhost:8080/v1/repos/lala110203?page=0&size=20
Accept: application/json
Authorization: Bearer {{cognito_token}}


### Actuator
GET http://localhost:8080/actuator


### Actuator Beans
GET http://localhost:8080/actuator/beans


### Swagger
GET http://localhost:8080/swagger-ui.html