vcs:
  type: github
  url: api.github.com
  pagination:
    per_page: 100

logging:
  level:
    root: INFO
    org.springframework.cloud.aws.secretsmanager: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  error:
    include-message: always
