vcs:
  type: github
  url: api.github.com

security:
  use-cognito-token: false

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  error:
    include-message: always
