### correct request
GET http://{{service_link}}:8080/v1/user/{{username}}/repos
Accept: application/json
Authorization: Bearer {{cognito_token}}

### correct request page1
GET http://{{service_link}}:8080/v1/user/{{username}}/repos?page=1&size=5
Accept: application/json
Authorization: Bearer {{cognito_token}}

### correct request page2
GET http://{{service_link}}:8080/v1/user/{{username}}/repos?page=2&size=5
Accept: application/json
Authorization: Bearer {{cognito_token}}

### wrong param
GET http://{{service_link}}:8080/v1/user/{{username}}/repos?page=2&size=-5
Accept: application/json
Authorization: Bearer {{cognito_token}}

### Actuator
GET http://{{service_link}}:8080/actuator/health


### wrong header
GET http://{{service_link}}:8080/v1/user/{{username}}/repos
Accept: application/xml
Authorization: Bearer {{cognito_token}}


### not existing repository
GET http://{{service_link}}:8080/v1/user/lala110203/repos?page=1&size=20
Accept: application/json
Authorization: Bearer {{cognito_token}}

